---
title: "Introducción"
author: "Francisco Vega"
date: "14-10-2021"
output: html_document
---



En el mundo actual hay muchos datos que se recopilan de forma automática, los deliveries son un ejemplo, allí se puede obtener información sobre la hora, que se pidió, el valor total, etc. Pero ¿qué se puede hacer con estos datos? Los datos nos pueden decir muchas cosas, siguiendo con el ejemplo de los deliveries, podemos obtener una lista con los productos más vendidos, analizar a qué hora hay más pedidos e incluso ver desde donde se realizan más pedidos para luego tomar decisiones corporativas como poner una sucursal mas cerca de un sector. En este informe se analizarán datos, provenientes de una pastelería en Corea, para responder las siguientes 6 preguntas:

1.  ¿Cuáles son los alimentos preferidos?

2.  ¿En qué días hay mayores ganancias?

3.  ¿Cuál es el rango de horario en el que hay más pedidos?

4.  ¿Qué relación hay entre los alimentos más vendidos y el horario?

5.  ¿Qué modelo puede predecir los pedidos que se realizarán en cierto rango horario?

6.  ¿En qué horarios la gente prefiere productos dulces por sobre los productos salados?

Por último, se buscará responder la siguiente pregunta ¿qué decisiones se pueden tomar con las respuestas obtenidas? Para ello, primero se presentará la base de datos y se darán detalles sobre sus variables, luego se hará un manejo de datos para poder analizarlos y poder responder las preguntas con los resultados de los diferentes análisis. Finalmente, se concluirá como estos datos pueden darnos la información necesaria para la toma de decisiones dentro de la pastelería.
